const SECRET_KEY = "u7S1;YOG'ps1s(?mgKxq&YCcN";
const API_KEY = "ny$@w4^AfI:ANeirYp*/Jxpw5l#";
const USER_PROVIDER_FACEBOOK = "USER_PROVIDER_FACEBOOK";
const USER_PROVIDER_GMAIL = "USER_PROVIDER_GMAIL";
const USER_PROVIDER_APP_AUTH = "USER_PROVIDER_APP_AUTH";

module.exports = {
  SECRET_KEY,
  API_KEY,
  USER_PROVIDER_APP_AUTH,
  USER_PROVIDER_GMAIL,
  USER_PROVIDER_FACEBOOK
};
